void drawChar(unsigned char ch, int x, int y, unsigned int attr, int zoom);
void drawInputCharacters(char ch, unsigned int attr, int zoom);
void drawString(int x, int y, char *str, unsigned int attr, int zoom);
void drawChar_double_buffering(unsigned char ch, int x, int y, unsigned int attr, int zoom);
void drawString_double_buffering(int x, int y, char *str, unsigned int attr, int zoom);
unsigned int uart_isReadByteReady();
unsigned char getUart();
void wait_us(uint64_t usVal);
void set_wait_timer(int set, uint64_t usVal);
void* memcpy(void *dest, const void *src, unsigned long n);
extern const char* welcome_message;
